name: 'Handle stale issues and PR'
on:
  schedule:
    - cron: '00 5,17 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: EndBug/workflows/.github/workflows/stale.yml@main
